[package]
name = "hecto_txt"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
log = "0.4.22"
log4rs = "1.3.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
