refresh_rate: 60 seconds

appenders:
  file_appender:
    kind: rolling_file
    path: "log/logs.log"
    append: true
    policy:
      trigger:
        kind: size
        limit: 2mb
      roller:
        kind: fixed_window
        base: 1
        count: 3
        pattern: "log/archive/archived_log_{}.log"
    
root:
  appenders:
    - file_appender
